branches:
  only: 
    - master

arch:
  - amd64
  - arm64

os: 
  - linux
  - windows
  - osx
  - freebsd

language: rust

rust:
  - stable

cache: cargo

script:
  - cargo build --verbose
  - cargo test --all-features -- --test-threads=1
